apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: gitea
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://dl.gitea.io/charts/'
    targetRevision: 6.0.3
    chart: gitea
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ingress.enabled
          value: 'true'
        - name: 'ingress.hosts[0].host'
          value: git.audryus.arpa
        - name: 'ingress.tls[0].secretName'
          value: 'chart-example-tls'
  project: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
