apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 2.0.6
    chart: argo-events
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true



