apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: cattle-system
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://releases.rancher.com/server-charts/latest'
    targetRevision: 2.6.9
    helm:
      values: |
        hostname: rancher.audryus.arpa
        ingress.extraAnnotations.'cert-manager\.io/cluster-issuer': cluster-issuer
        replicas: 1
    chart: rancher
  project: rancher
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
