apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    name: ''
    namespace: grafana
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.43.5
    chart: grafana
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/linkerd/linkerd2/main/grafana/values.yaml
  project: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
