apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-viz
spec:
  destination:
    name: ''
    namespace: linkerd-viz
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.linkerd.io/stable'
    targetRevision: 30.3.4
    chart: linkerd-viz
    helm:
      parameters:
        - name: dashboard.enforcedHostRegexp
          value: ^linkerd\.audryus\.arpa$
        - name: jaegerUrl
          value: jaeger.linkerd-jaeger:16686
        - name: grafana.url
          value: grafana.grafana:3000
  project: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
