apiVersion: v1
kind: Service
metadata:
  name: ubiquitous-spoon
  namespace: ubiquitous-spoon
  labels:
    app: ubiquitous-spoon
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: ubiquitous-spoon