apiVersion: v1
kind: Service
metadata:
  name: ubiquitous-spoon
  namespace: ubiquitous-spoon
  labels:
    app: ubiquitous-spoon
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ubiquitous-spoon