apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://download.elastic.co/downloads/eck/2.6.1/crds.yaml
- https://download.elastic.co/downloads/eck/2.6.1/operator.yaml
- rbac.yaml
- elastic.yaml
- kibana.yaml
- agents.yaml
- apmserver.yaml
- route.yaml
namespace: elastic-system
