apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
bases:
- http://github.com/argoproj/argo-workflows/releases/download/v3.4.3/install.yaml
patchesStrategicMerge:
- argo-server.yaml
