apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-prometheus
  namespace: monitoring
spec:
  secretName: tls-prometheus
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.audryus.arpa