apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    ubiquitous-spoon:
      port: "12000"
      endpoint: /ubiquitous-spoon
      method: POST