apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-apps
  namespace: ubiquitous-spoon
spec:
  secretName: tls-apps
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - apps.audryus.arpa