apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-ubiquitous-spoon
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["audryus.arpa"]
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /ubiquitous-spoon
      - headers:
          - name: X-Forwarded-Proto
            value: http
      filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
          port: 443
      backendRefs:
      - name: ubiquitous-spoon
        weight: 1
        port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /ubiquitous-spoon
      backendRefs:
      - name: ubiquitous-spoon
        weight: 1
        port: 80