---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-ubiquitous-spoon
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["audryus.arpa"]
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: "/ubiquitous-spoon"
      filters:
      - type: URLRewrite
        urlRewrite:
          hostname: ubiquitous-spoon.audryus.arpa
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: ""
      backendRefs:
      - name: ubiquitous-spoon
        port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-ubiquitous-spoon-two
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["ubiquitous-spoon.audryus.arpa"]
  rules:
    - backendRefs:
      - name: ubiquitous-spoon
        port: 80