apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-ubiquitous-spoon
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["audryus.arpa"]
  rules:
    - matches:
      - path:
          type: Exact
          value: /ubiquitous-spoon/
      backendRefs:
      - name: ubiquitous-spoon
        port: 80
    - matches:
      - path:
          type: Exact
          value: /ubiquitous-spoon
      backendRefs:
      - name: ubiquitous-spoon
        port: 80
