apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  labels:
    name: oci
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: argo
  source:
    path: argo-rollouts/overlays/oci
    repoURL: https://github.com/audryus/gitops-argo
    targetRevision: HEAD
  destination:
    namespace: argo-rollouts
    name: oci-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

