---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-managar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Cert Manager Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: oci-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-managar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cert-managar
  source:
    path: cert-managar
    repoURL: https://github.com/audryus/gitops-argo
    targetRevision: HEAD
  destination:
    namespace: cert-managar
    name: oci-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true