apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route-authentik
  namespace: authentik
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["authentik.audryus.arpa"]
  rules:
    - backendRefs:
      - name: authentik
        weight: 1
        port: 80