apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-apps
  namespace: istio-system
spec:
  secretName: tls-apps
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.audryus.arpa"