apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: Sky Walking
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: skywalking
  source:
    path: skywalking/overlays/dev
    repoURL: https://github.com/audryus/gitops-argo
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

