apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: ubiquitous-spoon=audryus/ubiquitous-spoon
    argocd-image-updater.argoproj.io/ubiquitous-spoon.update-strategy: semver
    argocd-image-updater.argoproj.io/ubiquitous-spoon.force-update: "true"
  name: ubiquitous-spoon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ubiquitous-spoon
  source:
    path: ubiquitous-spoon/overlays/dev
    repoURL: https://github.com/audryus/gitops-argo
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: ubiquitous-spoon
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true