apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k6-operator-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: k6-operator
  source:
    path: k6-operator/manager
    repoURL: https://github.com/audryus/gitops-argo
    targetRevision: HEAD
  destination:
    namespace: k6-operator-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

