apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: grafana
  namespace: istio-system
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-system
  hostnames: ["grafana.localdev.arpa"]
  rules:
    - backendRefs:
      - name: grafana
        weight: 1
        port: 3000