apiVersion: v1
kind: Service
metadata:
  name: silly-app
  labels:
    app: silly-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: silly-app