apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- http://github.com/argoproj/argo-workflows/releases/download/v3.4.3/install.yaml
- traefik-mdw-redirecttohttps.yaml
- cert.yaml
- ingress.yaml
namespace: argo
patches:
- argo-server.yaml
