apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: istio
  source:
    path: ''
    repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.16.0
    chart: istiod
    helm: 
      values: |
        meshConfig:
          defaultConfig:
            discoveryAddress: istiod.istio-system.svc:15012
          enableTracing: true
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
