apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: silly-app
  namespace: argo-events
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: ubiquitous-spoon
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ubiquitous-spoon-
              spec:
                workflowTemplateRef: 
                  name: ubiquitous-spoon

