apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: silly-app
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: ubiquitous-spoon
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ubiquitous-spoon-
                namespace: argo-events
              spec:
                volumes:
                  - name: docker-config
                    secret:
                      secretName: docker-config
                      items:
                        - key: "config.json"
                          path: config.json
                entrypoint: build
                serviceAccountName: operate-workflow-sa
                templates:
                  - name: build
                    dag:
                      tasks:
                      - name: build
                        templateRef:
                          name: container-image
                          template: build-kaniko-git
                          clusterScope: true
                        arguments:
                          parameters:
                          - name: repo_url
                            value: "git://github.com/audryus/ubiquitous-spoon.git"
                          - name: container_image
                            value: audryus/silly-app
                          - name: container_tag
                            value: "1.4"