apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-apps
  namespace: silly-app
spec:
  secretName: tls-apps
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - appz.audryus.arpa