apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: oci-istio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Istio Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    name: oci-cluster
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'