apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-gogs
  namespace: gogs
spec:
  secretName: tls-gogs
  issuerRef:
    name: cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - gogs.audryus.arpa